### ISSUE TITLE
冒泡排序结果正确，但过程有误

### ISSUE THREAD

**Issue by ddaysun** [umdreamer/course_python#4]
def mysort(seq,flag='<'):
   n=len(seq)
   if flag=='<':
        for i in range(n-1):
            for j in range(0,n-i-1):

                if seq[j]>seq[j+1]:

                    seq[j],seq[j+1]=seq[j+1],seq[j]
                print('=======',seq)
        print(seq)
   elif flag=='>':
       for i in range(n-1):
           for j in range(i,n-1-i):
               if seq[j]>seq[j+1]:
                seq[j],seq[j+1]= seq[j+1],seq[j]
   else:
       print('排序方式不正确')

def main():
    sequence=[3.0,2.0,1.0,5.0,4.0]
    flag='<'
    mysort(sequence)
    print(sequence)
    flag='>'
    mysort(sequence)
    print(sequence)

main()

**Comment by umdreamer** [comment]
你的这个缩进完全不对，请重新排版。使用code的模块，写法是三个三引号，中间写Python代码：

```python
# this is a python code
def foo(a, b):
    return a + b
```
这样，就是一个python的语句。

**Comment by ddaysun** [comment]
def mysort(seq, flag='<'):
    n = len(seq)
    if flag == '<':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] > seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
        print('=======', seq)
    elif flag == '>':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] < seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
    else:
        print('排序方式不正确')


def main():
    sequence = [3, 2, 1, 5, 4]
    mysort(sequence)
    print(sequence)


main()

**Comment by ddaysun** [comment]
`def mysort(seq, flag='<'):
    n = len(seq)
    if flag == '<':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] > seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
        print('=======', seq)
    elif flag == '>':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] < seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
    else:
        print('排序方式不正确')


def main():
    sequence = [3, 2, 1, 5, 4]
    mysort(sequence)
    print(sequence)


main()
`

**Comment by ddaysun** [comment]
`def mysort(seq, flag='<'):
    n = len(seq)
    if flag == '<':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] > seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
        print('=======', seq)
    elif flag == '>':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] < seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
    else:
        print('排序方式不正确')


def main():
    sequence = [3, 2, 1, 5, 4]
    mysort(sequence)
    print(sequence)


main()
`

**Comment by ddaysun** [comment]
[Uploading 新建文本文档.txt…]()

**Comment by ddaysun** [comment]
```
def mysort(seq, flag='<'):
    n = len(seq)
    if flag == '<':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] > seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
        print('=======', seq)
    elif flag == '>':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] < seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
    else:
        print('排序方式不正确')


def main():
    sequence = [3, 2, 1, 5, 4]
    mysort(sequence)
    print(sequence)


main()

```

**Comment by ddaysun** [comment]
老师，我找到了我的问题了，是缩进有问题，我刚提交的走了一遍就没问题

**Comment by umdreamer** [comment]
OK，确认问题就好。

**Comment by ddaysun** [comment]
正确代码
```
def mysort(seq, flag):
    n = len(seq)
    if flag == '<':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] > seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]

    elif flag == '>':
        for i in range(0, n - 1):
            for j in range(0, n - i - 1):
                if seq[j] < seq[j + 1]:
                    seq[j], seq[j + 1] = seq[j + 1], seq[j]
    else:
        print('排序方式不正确')


def main():
    sequence = [3, 2, 1, 5, 4]
    mysort(sequence, "<")
    print(sequence)
    mysort(sequence, ">")
    print(sequence)


main() 
```
